version: "3.0"

services:
  neo4j-4.4:
    image: neo4j:4.4.27-community
    labels:
        - "boltVersions=4.0,4.1,4.2,4.3,4.4"
        - "database=neo4j"
    ports:
      - 7689:7687
    environment:
      - NEO4J_AUTH=neo4j/boltxPassword
  neo4j-5.13.0:
    image: neo4j:5.13.0-community
    labels:
        - "boltVersions=5.0,5.1,5.2,5.3,5.4"
        - "database=neo4j"
    ports:
      - 7690:7687
    environment:
      - NEO4J_AUTH=neo4j/boltxPassword